### ISSUE TITLE
I'm curious about 2024

### ISSUE THREAD

**Issue by chuongmep** [NeVeSpl/RevitTestLibrary#1]
Dear @NeVeSpl 

Do you think it is best if you can publish full library to see ? 
I'm working on version Revit 2024 and Visual Studio 2022 and I want to try whether it will work or not.
Thank you !

**Comment by NeVeSpl** [comment]
It should work, I haven't updated docs, but there is an attribute that allows you to choose Revit version:

``[RunOn(RevitVer.Revit2024)]``

https://github.com/NeVeSpl/RevitDBExplorer/blob/c7b3b469444533d3e3694690ddbd3dd06b6ce99f/tests/RDQ/QueryParserTests.cs#L11

**Comment by chuongmep** [comment]
Hi @NeVeSpl , it also meaning we don't need load file `.runsettings` ?

**Comment by NeVeSpl** [comment]
You can always try without it, but it rather will not work. As far as I remember it is mandatory.

**Comment by chuongmep** [comment]
Thank you, @NeVeSpl, do you know reason why it not work with version lower 2023 ?

**Comment by NeVeSpl** [comment]
nuget it is build with revit 2023 DLLs, so I would expect that it will work only with Revit 2023 and 2024

**Comment by chuongmep** [comment]
Thanks for clearly for me, I just want to confirm with anybody want to try it : 
- for <2023 is not working now
- Rider is not working now 
- 2023 and 2024 is good 
[2023-09-08-17-13-25-628___706d190a-f28d-41fc-bf0c-357320b87f1e.log](https://github.com/NeVeSpl/RevitTestLibrary/files/12557762/2023-09-08-17-13-25-628___706d190a-f28d-41fc-bf0c-357320b87f1e.log)
