### ISSUE TITLE
Can we publish full source

### ISSUE THREAD

**Issue by chuongmep** [NeVeSpl/RevitTestLibrary#2]
Dear @NeVeSpl ,
I’m need customize some code inside your project library to integrate with Revit Addin manager, any chance can publish full source code ? It really useful !

**Comment by NeVeSpl** [comment]
This library will not be open-source in any time soon. I instead thought about making commercial product from it, with licensing similar to VisualStudio, with free licenses for not very profitable projects.

**Comment by chuongmep** [comment]
Thank you for your information @NeVeSpl
